In [35]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(5)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [37]:
df.set_index("entity")

            code  year  life_expectancy_0
entity
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [ ]:
df.rename(columns={'entity': 'Pais'}, inplace=True)
#df.set_index(["entity","year"], inplace=True)
df.head(3)

          Pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [2]:
df.loc[df["entity"].str.contains("UNI", case=False, regex=True)]

                             entity code  year  life_expectancy_0
15803                       Reunion  REU  1950            47.5602
15804                       Reunion  REU  1951            48.6476
15805                       Reunion  REU  1952            50.1082
15806                       Reunion  REU  1953            51.4650
15807                       Reunion  REU  1954            52.9912
...                             ...  ...   ...                ...
20581  United States Virgin Islands  VIR  2019            74.8761
20582  United States Virgin Islands  VIR  2020            74.7137
20583  United States Virgin Islands  VIR  2021            74.6132
20584  United States Virgin Islands  VIR  2022            75.0449
20585  United States Virgin Islands  VIR  2023            75.4724

[666 rows x 4 columns]

In [10]:
#.isnull()
#.notnull()
df.dropna(subset="code", inplace=True)
df.isnull().sum

<bound method DataFrame.sum of        entity   code   year  life_expectancy_0
0       False  False  False              False
1       False  False  False              False
2       False  False  False              False
3       False  False  False              False
4       False  False  False              False
...       ...    ...    ...                ...
21560   False  False  False              False
21561   False  False  False              False
21562   False  False  False              False
21563   False  False  False              False
21564   False  False  False              False

[20217 rows x 4 columns]>

In [28]:
df_groupby = df[df["year"] == 2020]
resultado = (
    df_groupby.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado

entity
Central African Republic    50.5959
Nigeria                     53.0724
Chad                        53.0818
Lesotho                     55.1325
Somalia                     57.0948
                             ...
Saint Barthelemy            84.0707
Macao                       84.6100
Japan                       84.6703
Hong Kong                   84.7073
Monaco                      86.0893
Name: life_expectancy_0, Length: 261, dtype: float64